# SPDX-FileCopyrightText: 2016-2026 Markus Katharina Brechtel <markus.katharina.brechtel@thengo.net>
#
# SPDX-License-Identifier: AGPL-3.0-or-later

---

- name: Deploy checker to the current system
  hosts: localhost
  become: true
  roles:
    - name: checker
    - name: system_checks
    - name: disk_checks
    - name: network_checks
    - name: notify_alerta
