[Distribution]
Distribution=debian

[Build]
CacheDirectory=mkosi.cache/

[Output]
OutputDirectory=mkosi.output/
Format=disk

[Content]
CleanPackageMetadata=no
Bootable=yes
UnifiedKernelImages=no
ShimBootloader=signed
Bootloader=grub-signed

Autologin=true

Packages=
	linux-image-generic
	grub-efi
	grub-efi-amd64
	grub-efi-amd64-signed
	tpm2-tools
	shim-signed
	systemd
	systemd-boot
	udev
	dbus-broker
	polkitd
	login
	sudo
	apt
	locales
	locales-all
	kitty-terminfo
	systemd-timesyncd
	tzdata
	bash
	fish
	jo
	ansible
	python3
	python3-pip
	procps
	iproute2
	curl
	vim
Locale=de_DE.UTF-8
LocaleMessages=C.UTF-8
Keymap=de
Timezone=Europe/Berlin

[Runtime]
Firmware=uefi-secure-boot
#Console=gui
RAM=8G
CPUs=4
