# SPDX-FileCopyrightText: 2016-2026 Markus Katharina Brechtel <markus.katharina.brechtel@thengo.net>
#
# SPDX-License-Identifier: AGPL-3.0-or-later

[Content]
Packages=
  linux-image-generic
  systemd
  udev
  dbus
  plymouth
  kmod
  systemd
  systemd-boot
  systemd-sysv
  systemd-container
  systemd-cryptsetup
  systemd-repart
  systemd-resolved
  systemd-timesyncd
  systemd-zram-generator
  tpm2-tools
  task-gnome-desktop
  bash
  dbus-broker
  iproute2
  iputils-ping
  linux-image-generic
  login
  polkitd
  systemd-coredump
  systemd-sysv
  tpm2-tools
  tzdata
