# SPDX-FileCopyrightText: 2016-2026 Markus Katharina Brechtel <markus.katharina.brechtel@thengo.net>
#
# SPDX-License-Identifier: AGPL-3.0-or-later

---

- name: ara pip package
  pip:
    name: "{{ansible_ara_pip_package}}"
    version: "{{ansible_ara_version}}"

- name: get ara ansible config
  shell: python3 -m ara.setup.ansible
  register: _ara_config
  changed_when: false
