# SPDX-FileCopyrightText: 2016-2026 Markus Katharina Brechtel <markus.katharina.brechtel@thengo.net>
#
# SPDX-License-Identifier: AGPL-3.0-or-later

---

- name: ansible etc directory
  file:
    path: /etc/ansible
    state: directory

- name: ansible config
  template:
    src: ansible.cfg.j2
    dest: /etc/ansible/ansible.cfg
