# SPDX-FileCopyrightText: 2016-2026 Markus Katharina Brechtel <markus.katharina.brechtel@thengo.net>
#
# SPDX-License-Identifier: AGPL-3.0-or-later

---

# packages setup
- import_role:
    name: debian_repos
  when:
    - ansible_distribution == "Debian"
    - not ansible_lsb.id is defined or ansible_lsb.id != "Raspbian"

- import_role:
    name: debian_packages
  when: ansible_distribution == "Debian"

# user setup
- import_role:
    name: root_user
- import_role:
    name: ssh_agent

# system setup
- import_role:
    name: hostname
  when:
    - not ansible_bender is defined
    - not container_type | default('') == 'podman'

- import_role:
    name: locales

- import_role:
    name: timezone
  when: not ansible_bender is defined

- import_role:
    name: keyboard
  when: not ansible_bender is defined

- import_role:
    name: network
- import_role:
    name: sysctl_tweaks

# shell setup
- import_role:
    name: fish
  tags:
    - fish
    - shells
